Implémentation de la fonction de reset iptables avec "./rezo reset"

diff --git a/rezo b/rezo
--- a/rezo
+++ b/rezo
@@ -127,10 +127,29 @@ function commande_show {
 }
 
 function commande_reset {
+
   echo
-  jaune "TODO: flush toutes tables iptables"
+  jaune "Arret du firewall et flush des tables iptables..."
   echo
+
+  ipt="/sbin/iptables"
+
+  ## Failsafe - die if /sbin/iptables not found
+  [ ! -x "$ipt" ] && { echo "$0: \"${ipt}\" command not found."; exit 1; }
+
+  $ipt -P INPUT ACCEPT
+  $ipt -P FORWARD ACCEPT
+  $ipt -P OUTPUT ACCEPT
+  $ipt -F
+  $ipt -X
+  $ipt -t nat -F
+  $ipt -t nat -X
+  $ipt -t mangle -F
+  $ipt -t mangle -X
+  $ipt -t raw -F
+  $ipt -t raw -X
 }
+
 
 function commande_scripts {
   echo
